import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { Link } from "wouter";
import { ArrowLeft, LockKeyhole, LogIn, Settings2 } from "lucide-react";

export default function Admin() {
  const { user, loading, isAuthenticated } = useAuth();

  if (loading) return <div className="flex min-h-screen items-center justify-center bg-[#fff8ef] text-[#8b1e23]">Carregando painel…</div>;
  if (!isAuthenticated) return <main className="paper-texture flex min-h-screen items-center justify-center bg-[#fff8ef] px-5"><div className="w-full max-w-md rounded-[2rem] border border-[#ead5c1] bg-white p-8 text-center shadow-[0_20px_70px_rgba(139,30,35,.1)]"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#fff0dc] text-[#ff6b35]"><LockKeyhole size={28} /></div><p className="mt-6 text-xs font-extrabold uppercase tracking-[.2em] text-[#ff6b35]">Área restrita</p><h1 className="font-display mt-2 text-4xl text-[#8b1e23]">Painel da Cantina</h1><p className="mt-3 text-sm leading-6 text-[#765e54]">Entre com a conta autorizada para gerenciar o cardápio e o status do restaurante.</p><button onClick={() => startLogin()} className="breathe mt-7 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#ff6b35] px-6 font-extrabold text-[#2b211d]"><LogIn size={18} /> Entrar</button><Link href="/" className="mt-5 flex items-center justify-center gap-2 text-sm font-bold text-[#8b1e23]"><ArrowLeft size={16} /> Voltar ao cardápio</Link></div></main>;
  if (user?.role !== "admin") return <main className="flex min-h-screen items-center justify-center bg-[#fff8ef] px-5"><div className="text-center"><LockKeyhole className="mx-auto text-[#a83232]" size={34} /><h1 className="font-display mt-4 text-3xl text-[#8b1e23]">Acesso não autorizado</h1><p className="mt-2 text-[#765e54]">Esta conta não possui permissão de administrador.</p><Link href="/" className="mt-5 inline-flex items-center gap-2 font-bold text-[#ff6b35]"><ArrowLeft size={16} /> Voltar</Link></div></main>;

  return <main className="paper-texture min-h-screen bg-[#fff8ef] px-5 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><img src="/manus-storage/logo_d54b5be6.png" alt="Cantina do Chalé Restaurante" className="h-16 w-16 rounded-full object-cover shadow-[0_8px_20px_rgba(139,30,35,.16)]" /><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#ff6b35]">Administração</p><h1 className="font-display mt-2 text-4xl text-[#8b1e23]">Painel da Cantina</h1></div></div><Link href="/" className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ead5c1] bg-white px-4 text-sm font-bold text-[#8b1e23]"><ArrowLeft size={16} /> Ver cardápio</Link></div><section className="mt-8 rounded-[2rem] border border-[#ead5c1] bg-white p-7"><div className="flex items-start gap-4"><div className="rounded-2xl bg-[#fff0dc] p-3 text-[#ff6b35]"><Settings2 size={24} /></div><div><h2 className="font-display text-2xl text-[#8b1e23]">Gestão do cardápio</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#765e54]">A estrutura do painel está protegida por login. O próximo bloco conecta categorias, produtos, disponibilidade e status ao banco de dados do projeto.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-[#fff8ef] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-[#765e54]">Produtos</p><strong className="mt-2 block text-3xl text-[#8b1e23]">0</strong><span className="text-sm text-[#765e54]">Aguardando cadastro</span></div><div className="rounded-2xl bg-[#fff8ef] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-[#765e54]">Categorias</p><strong className="mt-2 block text-3xl text-[#8b1e23]">4</strong><span className="text-sm text-[#765e54]">Estrutura inicial</span></div><div className="rounded-2xl bg-[#fff8ef] p-5"><p className="text-xs font-extrabold uppercase tracking-wider text-[#765e54]">Status</p><strong className="mt-2 block text-3xl text-[#2e7d5b]">Aberto</strong><span className="text-sm text-[#765e54]">Configurável</span></div></div></section></div></main>;
}
